// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/chess/v1/chess.proto

package chessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerColor int32

const (
	PlayerColor_PLAYER_COLOR_UNSPECIFIED PlayerColor = 0
	PlayerColor_PLAYER_COLOR_WHITE       PlayerColor = 1
	PlayerColor_PLAYER_COLOR_BLACK       PlayerColor = 2
)

// Enum value maps for PlayerColor.
var (
	PlayerColor_name = map[int32]string{
		0: "PLAYER_COLOR_UNSPECIFIED",
		1: "PLAYER_COLOR_WHITE",
		2: "PLAYER_COLOR_BLACK",
	}
	PlayerColor_value = map[string]int32{
		"PLAYER_COLOR_UNSPECIFIED": 0,
		"PLAYER_COLOR_WHITE":       1,
		"PLAYER_COLOR_BLACK":       2,
	}
)

func (x PlayerColor) Enum() *PlayerColor {
	p := new(PlayerColor)
	*p = x
	return p
}

func (x PlayerColor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerColor) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chess_v1_chess_proto_enumTypes[0].Descriptor()
}

func (PlayerColor) Type() protoreflect.EnumType {
	return &file_proto_chess_v1_chess_proto_enumTypes[0]
}

func (x PlayerColor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerColor.Descriptor instead.
func (PlayerColor) EnumDescriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{0}
}

type GameStatus int32

const (
	GameStatus_GAME_STATUS_UNSPECIFIED GameStatus = 0
	GameStatus_GAME_STATUS_NOT_STARTED GameStatus = 1
	GameStatus_GAME_STATUS_IN_PROGRESS GameStatus = 2
	GameStatus_GAME_STATUS_FINISHED    GameStatus = 3
)

// Enum value maps for GameStatus.
var (
	GameStatus_name = map[int32]string{
		0: "GAME_STATUS_UNSPECIFIED",
		1: "GAME_STATUS_NOT_STARTED",
		2: "GAME_STATUS_IN_PROGRESS",
		3: "GAME_STATUS_FINISHED",
	}
	GameStatus_value = map[string]int32{
		"GAME_STATUS_UNSPECIFIED": 0,
		"GAME_STATUS_NOT_STARTED": 1,
		"GAME_STATUS_IN_PROGRESS": 2,
		"GAME_STATUS_FINISHED":    3,
	}
)

func (x GameStatus) Enum() *GameStatus {
	p := new(GameStatus)
	*p = x
	return p
}

func (x GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chess_v1_chess_proto_enumTypes[1].Descriptor()
}

func (GameStatus) Type() protoreflect.EnumType {
	return &file_proto_chess_v1_chess_proto_enumTypes[1]
}

func (x GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameStatus.Descriptor instead.
func (GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{0}
}

type GetByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRequest) Reset() {
	*x = GetByIdRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRequest) ProtoMessage() {}

func (x *GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByIdRequest) Reset() {
	*x = DeleteByIdRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByIdRequest) ProtoMessage() {}

func (x *DeleteByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{3}
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         PlayerColor            `protobuf:"varint,3,opt,name=color,proto3,enum=chess.v1.PlayerColor" json:"color,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{5}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetColor() PlayerColor {
	if x != nil {
		return x.Color
	}
	return PlayerColor_PLAYER_COLOR_UNSPECIFIED
}

func (x *Player) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{6}
}

func (x *Board) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Board) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Board) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Game struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WhitePlayerName    string                 `protobuf:"bytes,2,opt,name=white_player_name,json=whitePlayerName,proto3" json:"white_player_name,omitempty"`
	BlackPlayerName    string                 `protobuf:"bytes,3,opt,name=black_player_name,json=blackPlayerName,proto3" json:"black_player_name,omitempty"`
	BoardSize          int32                  `protobuf:"varint,4,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`
	Status             GameStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=chess.v1.GameStatus" json:"status,omitempty"`
	CurrentPlayerColor PlayerColor            `protobuf:"varint,6,opt,name=current_player_color,json=currentPlayerColor,proto3,enum=chess.v1.PlayerColor" json:"current_player_color,omitempty"`
	WinnerColor        PlayerColor            `protobuf:"varint,7,opt,name=winner_color,json=winnerColor,proto3,enum=chess.v1.PlayerColor" json:"winner_color,omitempty"`
	Rows               []*Row                 `protobuf:"bytes,8,rep,name=rows,proto3" json:"rows,omitempty"` // состояние доски (cells)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{7}
}

func (x *Game) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Game) GetWhitePlayerName() string {
	if x != nil {
		return x.WhitePlayerName
	}
	return ""
}

func (x *Game) GetBlackPlayerName() string {
	if x != nil {
		return x.BlackPlayerName
	}
	return ""
}

func (x *Game) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *Game) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

func (x *Game) GetCurrentPlayerColor() PlayerColor {
	if x != nil {
		return x.CurrentPlayerColor
	}
	return PlayerColor_PLAYER_COLOR_UNSPECIFIED
}

func (x *Game) GetWinnerColor() PlayerColor {
	if x != nil {
		return x.WinnerColor
	}
	return PlayerColor_PLAYER_COLOR_UNSPECIFIED
}

func (x *Game) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId        int32                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FromRow       int32                  `protobuf:"varint,3,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,4,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,5,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,6,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	Piece         string                 `protobuf:"bytes,7,opt,name=piece,proto3" json:"piece,omitempty"`
	Notation      string                 `protobuf:"bytes,8,opt,name=notation,proto3" json:"notation,omitempty"`
	Player        string                 `protobuf:"bytes,9,opt,name=player,proto3" json:"player,omitempty"` // display name (как в REST)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{8}
}

func (x *Move) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Move) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *Move) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *Move) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *Move) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *Move) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *Move) GetPiece() string {
	if x != nil {
		return x.Piece
	}
	return ""
}

func (x *Move) GetNotation() string {
	if x != nil {
		return x.Notation
	}
	return ""
}

func (x *Move) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Color         PlayerColor            `protobuf:"varint,2,opt,name=color,proto3,enum=chess.v1.PlayerColor" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePlayerRequest) GetColor() PlayerColor {
	if x != nil {
		return x.Color
	}
	return PlayerColor_PLAYER_COLOR_UNSPECIFIED
}

type UpdatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         PlayerColor            `protobuf:"varint,3,opt,name=color,proto3,enum=chess.v1.PlayerColor" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePlayerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePlayerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlayerRequest) GetColor() PlayerColor {
	if x != nil {
		return x.Color
	}
	return PlayerColor_PLAYER_COLOR_UNSPECIFIED
}

type ListPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Player              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersResponse) Reset() {
	*x = ListPlayersResponse{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersResponse) ProtoMessage() {}

func (x *ListPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersResponse.ProtoReflect.Descriptor instead.
func (*ListPlayersResponse) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{11}
}

func (x *ListPlayersResponse) GetItems() []*Player {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{12}
}

func (x *CreateBoardRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UpdateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBoardRequest) Reset() {
	*x = UpdateBoardRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBoardRequest) ProtoMessage() {}

func (x *UpdateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBoardRequest.ProtoReflect.Descriptor instead.
func (*UpdateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateBoardRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBoardRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UpdateBoardRequest) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type ListBoardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Board               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBoardsResponse) Reset() {
	*x = ListBoardsResponse{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBoardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBoardsResponse) ProtoMessage() {}

func (x *ListBoardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBoardsResponse.ProtoReflect.Descriptor instead.
func (*ListBoardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{14}
}

func (x *ListBoardsResponse) GetItems() []*Board {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateGameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WhitePlayerName string                 `protobuf:"bytes,1,opt,name=white_player_name,json=whitePlayerName,proto3" json:"white_player_name,omitempty"`
	BlackPlayerName string                 `protobuf:"bytes,2,opt,name=black_player_name,json=blackPlayerName,proto3" json:"black_player_name,omitempty"`
	BoardSize       int32                  `protobuf:"varint,3,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{15}
}

func (x *CreateGameRequest) GetWhitePlayerName() string {
	if x != nil {
		return x.WhitePlayerName
	}
	return ""
}

func (x *CreateGameRequest) GetBlackPlayerName() string {
	if x != nil {
		return x.BlackPlayerName
	}
	return ""
}

func (x *CreateGameRequest) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

type UpdateGameRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WhitePlayerName string                 `protobuf:"bytes,2,opt,name=white_player_name,json=whitePlayerName,proto3" json:"white_player_name,omitempty"`
	BlackPlayerName string                 `protobuf:"bytes,3,opt,name=black_player_name,json=blackPlayerName,proto3" json:"black_player_name,omitempty"`
	BoardSize       int32                  `protobuf:"varint,4,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`
	Status          GameStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=chess.v1.GameStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateGameRequest) Reset() {
	*x = UpdateGameRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameRequest) ProtoMessage() {}

func (x *UpdateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateGameRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGameRequest) GetWhitePlayerName() string {
	if x != nil {
		return x.WhitePlayerName
	}
	return ""
}

func (x *UpdateGameRequest) GetBlackPlayerName() string {
	if x != nil {
		return x.BlackPlayerName
	}
	return ""
}

func (x *UpdateGameRequest) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *UpdateGameRequest) GetStatus() GameStatus {
	if x != nil {
		return x.Status
	}
	return GameStatus_GAME_STATUS_UNSPECIFIED
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Game                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{17}
}

func (x *ListGamesResponse) GetItems() []*Game {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateMoveRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	GameId int32                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	// либо нотация, либо координаты
	Notation      string `protobuf:"bytes,2,opt,name=notation,proto3" json:"notation,omitempty"`
	FromRow       int32  `protobuf:"varint,3,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32  `protobuf:"varint,4,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32  `protobuf:"varint,5,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32  `protobuf:"varint,6,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMoveRequest) Reset() {
	*x = CreateMoveRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMoveRequest) ProtoMessage() {}

func (x *CreateMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMoveRequest.ProtoReflect.Descriptor instead.
func (*CreateMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{18}
}

func (x *CreateMoveRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CreateMoveRequest) GetNotation() string {
	if x != nil {
		return x.Notation
	}
	return ""
}

func (x *CreateMoveRequest) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *CreateMoveRequest) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *CreateMoveRequest) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *CreateMoveRequest) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

type UpdateMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GameId        int32                  `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	FromRow       int32                  `protobuf:"varint,3,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromCol       int32                  `protobuf:"varint,4,opt,name=from_col,json=fromCol,proto3" json:"from_col,omitempty"`
	ToRow         int32                  `protobuf:"varint,5,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToCol         int32                  `protobuf:"varint,6,opt,name=to_col,json=toCol,proto3" json:"to_col,omitempty"`
	Piece         string                 `protobuf:"bytes,7,opt,name=piece,proto3" json:"piece,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMoveRequest) Reset() {
	*x = UpdateMoveRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMoveRequest) ProtoMessage() {}

func (x *UpdateMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMoveRequest.ProtoReflect.Descriptor instead.
func (*UpdateMoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateMoveRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMoveRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *UpdateMoveRequest) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *UpdateMoveRequest) GetFromCol() int32 {
	if x != nil {
		return x.FromCol
	}
	return 0
}

func (x *UpdateMoveRequest) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *UpdateMoveRequest) GetToCol() int32 {
	if x != nil {
		return x.ToCol
	}
	return 0
}

func (x *UpdateMoveRequest) GetPiece() string {
	if x != nil {
		return x.Piece
	}
	return ""
}

type ListMovesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        int32                  `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"` // 0 = все
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMovesRequest) Reset() {
	*x = ListMovesRequest{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMovesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovesRequest) ProtoMessage() {}

func (x *ListMovesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovesRequest.ProtoReflect.Descriptor instead.
func (*ListMovesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{20}
}

func (x *ListMovesRequest) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type ListMovesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Move                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMovesResponse) Reset() {
	*x = ListMovesResponse{}
	mi := &file_proto_chess_v1_chess_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMovesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMovesResponse) ProtoMessage() {}

func (x *ListMovesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_v1_chess_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMovesResponse.ProtoReflect.Descriptor instead.
func (*ListMovesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chess_v1_chess_proto_rawDescGZIP(), []int{21}
}

func (x *ListMovesResponse) GetItems() []*Move {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_chess_v1_chess_proto protoreflect.FileDescriptor

const file_proto_chess_v1_chess_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/chess/v1/chess.proto\x12\bchess.v1\"\a\n" +
	"\x05Empty\" \n" +
	"\x0eGetByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"#\n" +
	"\x11DeleteByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\r\n" +
	"\vListRequest\"\x1b\n" +
	"\x03Row\x12\x14\n" +
	"\x05cells\x18\x01 \x03(\tR\x05cells\"q\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x05color\x18\x03 \x01(\x0e2\x15.chess.v1.PlayerColorR\x05color\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\"N\n" +
	"\x05Board\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12!\n" +
	"\x04rows\x18\x03 \x03(\v2\r.chess.v1.RowR\x04rows\"\xe1\x02\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12*\n" +
	"\x11white_player_name\x18\x02 \x01(\tR\x0fwhitePlayerName\x12*\n" +
	"\x11black_player_name\x18\x03 \x01(\tR\x0fblackPlayerName\x12\x1d\n" +
	"\n" +
	"board_size\x18\x04 \x01(\x05R\tboardSize\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.chess.v1.GameStatusR\x06status\x12G\n" +
	"\x14current_player_color\x18\x06 \x01(\x0e2\x15.chess.v1.PlayerColorR\x12currentPlayerColor\x128\n" +
	"\fwinner_color\x18\a \x01(\x0e2\x15.chess.v1.PlayerColorR\vwinnerColor\x12!\n" +
	"\x04rows\x18\b \x03(\v2\r.chess.v1.RowR\x04rows\"\xdd\x01\n" +
	"\x04Move\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x05R\x06gameId\x12\x19\n" +
	"\bfrom_row\x18\x03 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x04 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x05 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x06 \x01(\x05R\x05toCol\x12\x14\n" +
	"\x05piece\x18\a \x01(\tR\x05piece\x12\x1a\n" +
	"\bnotation\x18\b \x01(\tR\bnotation\x12\x16\n" +
	"\x06player\x18\t \x01(\tR\x06player\"V\n" +
	"\x13CreatePlayerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x05color\x18\x02 \x01(\x0e2\x15.chess.v1.PlayerColorR\x05color\"f\n" +
	"\x13UpdatePlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x05color\x18\x03 \x01(\x0e2\x15.chess.v1.PlayerColorR\x05color\"=\n" +
	"\x13ListPlayersResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.chess.v1.PlayerR\x05items\"(\n" +
	"\x12CreateBoardRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"[\n" +
	"\x12UpdateBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12!\n" +
	"\x04rows\x18\x03 \x03(\v2\r.chess.v1.RowR\x04rows\";\n" +
	"\x12ListBoardsResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.chess.v1.BoardR\x05items\"\x8a\x01\n" +
	"\x11CreateGameRequest\x12*\n" +
	"\x11white_player_name\x18\x01 \x01(\tR\x0fwhitePlayerName\x12*\n" +
	"\x11black_player_name\x18\x02 \x01(\tR\x0fblackPlayerName\x12\x1d\n" +
	"\n" +
	"board_size\x18\x03 \x01(\x05R\tboardSize\"\xc8\x01\n" +
	"\x11UpdateGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12*\n" +
	"\x11white_player_name\x18\x02 \x01(\tR\x0fwhitePlayerName\x12*\n" +
	"\x11black_player_name\x18\x03 \x01(\tR\x0fblackPlayerName\x12\x1d\n" +
	"\n" +
	"board_size\x18\x04 \x01(\x05R\tboardSize\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.chess.v1.GameStatusR\x06status\"9\n" +
	"\x11ListGamesResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.chess.v1.GameR\x05items\"\xac\x01\n" +
	"\x11CreateMoveRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x05R\x06gameId\x12\x1a\n" +
	"\bnotation\x18\x02 \x01(\tR\bnotation\x12\x19\n" +
	"\bfrom_row\x18\x03 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x04 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x05 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x06 \x01(\x05R\x05toCol\"\xb6\x01\n" +
	"\x11UpdateMoveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x05R\x06gameId\x12\x19\n" +
	"\bfrom_row\x18\x03 \x01(\x05R\afromRow\x12\x19\n" +
	"\bfrom_col\x18\x04 \x01(\x05R\afromCol\x12\x15\n" +
	"\x06to_row\x18\x05 \x01(\x05R\x05toRow\x12\x15\n" +
	"\x06to_col\x18\x06 \x01(\x05R\x05toCol\x12\x14\n" +
	"\x05piece\x18\a \x01(\tR\x05piece\"+\n" +
	"\x10ListMovesRequest\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\x05R\x06gameId\"9\n" +
	"\x11ListMovesResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.chess.v1.MoveR\x05items*[\n" +
	"\vPlayerColor\x12\x1c\n" +
	"\x18PLAYER_COLOR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PLAYER_COLOR_WHITE\x10\x01\x12\x16\n" +
	"\x12PLAYER_COLOR_BLACK\x10\x02*}\n" +
	"\n" +
	"GameStatus\x12\x1b\n" +
	"\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17GAME_STATUS_NOT_STARTED\x10\x01\x12\x1b\n" +
	"\x17GAME_STATUS_IN_PROGRESS\x10\x02\x12\x18\n" +
	"\x14GAME_STATUS_FINISHED\x10\x032\xcd\x02\n" +
	"\rPlayerService\x12?\n" +
	"\fCreatePlayer\x12\x1d.chess.v1.CreatePlayerRequest\x1a\x10.chess.v1.Player\x12?\n" +
	"\fUpdatePlayer\x12\x1d.chess.v1.UpdatePlayerRequest\x1a\x10.chess.v1.Player\x12<\n" +
	"\fDeletePlayer\x12\x1b.chess.v1.DeleteByIdRequest\x1a\x0f.chess.v1.Empty\x127\n" +
	"\tGetPlayer\x12\x18.chess.v1.GetByIdRequest\x1a\x10.chess.v1.Player\x12C\n" +
	"\vListPlayers\x12\x15.chess.v1.ListRequest\x1a\x1d.chess.v1.ListPlayersResponse2\xc1\x02\n" +
	"\fBoardService\x12<\n" +
	"\vCreateBoard\x12\x1c.chess.v1.CreateBoardRequest\x1a\x0f.chess.v1.Board\x12<\n" +
	"\vUpdateBoard\x12\x1c.chess.v1.UpdateBoardRequest\x1a\x0f.chess.v1.Board\x12;\n" +
	"\vDeleteBoard\x12\x1b.chess.v1.DeleteByIdRequest\x1a\x0f.chess.v1.Empty\x125\n" +
	"\bGetBoard\x12\x18.chess.v1.GetByIdRequest\x1a\x0f.chess.v1.Board\x12A\n" +
	"\n" +
	"ListBoards\x12\x15.chess.v1.ListRequest\x1a\x1c.chess.v1.ListBoardsResponse2\xb5\x02\n" +
	"\vGameService\x129\n" +
	"\n" +
	"CreateGame\x12\x1b.chess.v1.CreateGameRequest\x1a\x0e.chess.v1.Game\x129\n" +
	"\n" +
	"UpdateGame\x12\x1b.chess.v1.UpdateGameRequest\x1a\x0e.chess.v1.Game\x12:\n" +
	"\n" +
	"DeleteGame\x12\x1b.chess.v1.DeleteByIdRequest\x1a\x0f.chess.v1.Empty\x123\n" +
	"\aGetGame\x12\x18.chess.v1.GetByIdRequest\x1a\x0e.chess.v1.Game\x12?\n" +
	"\tListGames\x12\x15.chess.v1.ListRequest\x1a\x1b.chess.v1.ListGamesResponse2\xba\x02\n" +
	"\vMoveService\x129\n" +
	"\n" +
	"CreateMove\x12\x1b.chess.v1.CreateMoveRequest\x1a\x0e.chess.v1.Move\x129\n" +
	"\n" +
	"UpdateMove\x12\x1b.chess.v1.UpdateMoveRequest\x1a\x0e.chess.v1.Move\x12:\n" +
	"\n" +
	"DeleteMove\x12\x1b.chess.v1.DeleteByIdRequest\x1a\x0f.chess.v1.Empty\x123\n" +
	"\aGetMove\x12\x18.chess.v1.GetByIdRequest\x1a\x0e.chess.v1.Move\x12D\n" +
	"\tListMoves\x12\x1a.chess.v1.ListMovesRequest\x1a\x1b.chess.v1.ListMovesResponseB/Z-github.com/imyakin/go_hw/gen/chess/v1;chessv1b\x06proto3"

var (
	file_proto_chess_v1_chess_proto_rawDescOnce sync.Once
	file_proto_chess_v1_chess_proto_rawDescData []byte
)

func file_proto_chess_v1_chess_proto_rawDescGZIP() []byte {
	file_proto_chess_v1_chess_proto_rawDescOnce.Do(func() {
		file_proto_chess_v1_chess_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chess_v1_chess_proto_rawDesc), len(file_proto_chess_v1_chess_proto_rawDesc)))
	})
	return file_proto_chess_v1_chess_proto_rawDescData
}

var file_proto_chess_v1_chess_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_chess_v1_chess_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_chess_v1_chess_proto_goTypes = []any{
	(PlayerColor)(0),            // 0: chess.v1.PlayerColor
	(GameStatus)(0),             // 1: chess.v1.GameStatus
	(*Empty)(nil),               // 2: chess.v1.Empty
	(*GetByIdRequest)(nil),      // 3: chess.v1.GetByIdRequest
	(*DeleteByIdRequest)(nil),   // 4: chess.v1.DeleteByIdRequest
	(*ListRequest)(nil),         // 5: chess.v1.ListRequest
	(*Row)(nil),                 // 6: chess.v1.Row
	(*Player)(nil),              // 7: chess.v1.Player
	(*Board)(nil),               // 8: chess.v1.Board
	(*Game)(nil),                // 9: chess.v1.Game
	(*Move)(nil),                // 10: chess.v1.Move
	(*CreatePlayerRequest)(nil), // 11: chess.v1.CreatePlayerRequest
	(*UpdatePlayerRequest)(nil), // 12: chess.v1.UpdatePlayerRequest
	(*ListPlayersResponse)(nil), // 13: chess.v1.ListPlayersResponse
	(*CreateBoardRequest)(nil),  // 14: chess.v1.CreateBoardRequest
	(*UpdateBoardRequest)(nil),  // 15: chess.v1.UpdateBoardRequest
	(*ListBoardsResponse)(nil),  // 16: chess.v1.ListBoardsResponse
	(*CreateGameRequest)(nil),   // 17: chess.v1.CreateGameRequest
	(*UpdateGameRequest)(nil),   // 18: chess.v1.UpdateGameRequest
	(*ListGamesResponse)(nil),   // 19: chess.v1.ListGamesResponse
	(*CreateMoveRequest)(nil),   // 20: chess.v1.CreateMoveRequest
	(*UpdateMoveRequest)(nil),   // 21: chess.v1.UpdateMoveRequest
	(*ListMovesRequest)(nil),    // 22: chess.v1.ListMovesRequest
	(*ListMovesResponse)(nil),   // 23: chess.v1.ListMovesResponse
}
var file_proto_chess_v1_chess_proto_depIdxs = []int32{
	0,  // 0: chess.v1.Player.color:type_name -> chess.v1.PlayerColor
	6,  // 1: chess.v1.Board.rows:type_name -> chess.v1.Row
	1,  // 2: chess.v1.Game.status:type_name -> chess.v1.GameStatus
	0,  // 3: chess.v1.Game.current_player_color:type_name -> chess.v1.PlayerColor
	0,  // 4: chess.v1.Game.winner_color:type_name -> chess.v1.PlayerColor
	6,  // 5: chess.v1.Game.rows:type_name -> chess.v1.Row
	0,  // 6: chess.v1.CreatePlayerRequest.color:type_name -> chess.v1.PlayerColor
	0,  // 7: chess.v1.UpdatePlayerRequest.color:type_name -> chess.v1.PlayerColor
	7,  // 8: chess.v1.ListPlayersResponse.items:type_name -> chess.v1.Player
	6,  // 9: chess.v1.UpdateBoardRequest.rows:type_name -> chess.v1.Row
	8,  // 10: chess.v1.ListBoardsResponse.items:type_name -> chess.v1.Board
	1,  // 11: chess.v1.UpdateGameRequest.status:type_name -> chess.v1.GameStatus
	9,  // 12: chess.v1.ListGamesResponse.items:type_name -> chess.v1.Game
	10, // 13: chess.v1.ListMovesResponse.items:type_name -> chess.v1.Move
	11, // 14: chess.v1.PlayerService.CreatePlayer:input_type -> chess.v1.CreatePlayerRequest
	12, // 15: chess.v1.PlayerService.UpdatePlayer:input_type -> chess.v1.UpdatePlayerRequest
	4,  // 16: chess.v1.PlayerService.DeletePlayer:input_type -> chess.v1.DeleteByIdRequest
	3,  // 17: chess.v1.PlayerService.GetPlayer:input_type -> chess.v1.GetByIdRequest
	5,  // 18: chess.v1.PlayerService.ListPlayers:input_type -> chess.v1.ListRequest
	14, // 19: chess.v1.BoardService.CreateBoard:input_type -> chess.v1.CreateBoardRequest
	15, // 20: chess.v1.BoardService.UpdateBoard:input_type -> chess.v1.UpdateBoardRequest
	4,  // 21: chess.v1.BoardService.DeleteBoard:input_type -> chess.v1.DeleteByIdRequest
	3,  // 22: chess.v1.BoardService.GetBoard:input_type -> chess.v1.GetByIdRequest
	5,  // 23: chess.v1.BoardService.ListBoards:input_type -> chess.v1.ListRequest
	17, // 24: chess.v1.GameService.CreateGame:input_type -> chess.v1.CreateGameRequest
	18, // 25: chess.v1.GameService.UpdateGame:input_type -> chess.v1.UpdateGameRequest
	4,  // 26: chess.v1.GameService.DeleteGame:input_type -> chess.v1.DeleteByIdRequest
	3,  // 27: chess.v1.GameService.GetGame:input_type -> chess.v1.GetByIdRequest
	5,  // 28: chess.v1.GameService.ListGames:input_type -> chess.v1.ListRequest
	20, // 29: chess.v1.MoveService.CreateMove:input_type -> chess.v1.CreateMoveRequest
	21, // 30: chess.v1.MoveService.UpdateMove:input_type -> chess.v1.UpdateMoveRequest
	4,  // 31: chess.v1.MoveService.DeleteMove:input_type -> chess.v1.DeleteByIdRequest
	3,  // 32: chess.v1.MoveService.GetMove:input_type -> chess.v1.GetByIdRequest
	22, // 33: chess.v1.MoveService.ListMoves:input_type -> chess.v1.ListMovesRequest
	7,  // 34: chess.v1.PlayerService.CreatePlayer:output_type -> chess.v1.Player
	7,  // 35: chess.v1.PlayerService.UpdatePlayer:output_type -> chess.v1.Player
	2,  // 36: chess.v1.PlayerService.DeletePlayer:output_type -> chess.v1.Empty
	7,  // 37: chess.v1.PlayerService.GetPlayer:output_type -> chess.v1.Player
	13, // 38: chess.v1.PlayerService.ListPlayers:output_type -> chess.v1.ListPlayersResponse
	8,  // 39: chess.v1.BoardService.CreateBoard:output_type -> chess.v1.Board
	8,  // 40: chess.v1.BoardService.UpdateBoard:output_type -> chess.v1.Board
	2,  // 41: chess.v1.BoardService.DeleteBoard:output_type -> chess.v1.Empty
	8,  // 42: chess.v1.BoardService.GetBoard:output_type -> chess.v1.Board
	16, // 43: chess.v1.BoardService.ListBoards:output_type -> chess.v1.ListBoardsResponse
	9,  // 44: chess.v1.GameService.CreateGame:output_type -> chess.v1.Game
	9,  // 45: chess.v1.GameService.UpdateGame:output_type -> chess.v1.Game
	2,  // 46: chess.v1.GameService.DeleteGame:output_type -> chess.v1.Empty
	9,  // 47: chess.v1.GameService.GetGame:output_type -> chess.v1.Game
	19, // 48: chess.v1.GameService.ListGames:output_type -> chess.v1.ListGamesResponse
	10, // 49: chess.v1.MoveService.CreateMove:output_type -> chess.v1.Move
	10, // 50: chess.v1.MoveService.UpdateMove:output_type -> chess.v1.Move
	2,  // 51: chess.v1.MoveService.DeleteMove:output_type -> chess.v1.Empty
	10, // 52: chess.v1.MoveService.GetMove:output_type -> chess.v1.Move
	23, // 53: chess.v1.MoveService.ListMoves:output_type -> chess.v1.ListMovesResponse
	34, // [34:54] is the sub-list for method output_type
	14, // [14:34] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_chess_v1_chess_proto_init() }
func file_proto_chess_v1_chess_proto_init() {
	if File_proto_chess_v1_chess_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chess_v1_chess_proto_rawDesc), len(file_proto_chess_v1_chess_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_chess_v1_chess_proto_goTypes,
		DependencyIndexes: file_proto_chess_v1_chess_proto_depIdxs,
		EnumInfos:         file_proto_chess_v1_chess_proto_enumTypes,
		MessageInfos:      file_proto_chess_v1_chess_proto_msgTypes,
	}.Build()
	File_proto_chess_v1_chess_proto = out.File
	file_proto_chess_v1_chess_proto_goTypes = nil
	file_proto_chess_v1_chess_proto_depIdxs = nil
}
